#ifndef SENTINEL_CERTS_H
#define SENTINEL_CERTS_H

/*
 * drivers/certs/certs.h  —  Embedded TLS Credentials for Zephyr
 * =============================================================
 * AUTO-GENERATED by scripts/gen_cert_headers.sh
 *
 * Do NOT edit manually.  Regenerate with:
 *   ./scripts/gen_cert_headers.sh
 *
 * This header embeds the server certificate, server private key, and CA
 * certificate as DER byte arrays so Zephyr's tls_credential_add() can load
 * them at boot without a filesystem.
 *
 * PLACEHOLDER — arrays below contain a single 0x00 byte.
 * Run gen_cert_headers.sh after generating certs to populate real data.
 */

/* ------------------------------------------------------------------
 * CA Certificate  (DER format)
 * tls_credential_add(TLS_CA_TAG, TLS_CREDENTIAL_CA_CERTIFICATE, ...)
 * ------------------------------------------------------------------ */
static const unsigned char ca_cert_der[] = {
    /* PLACEHOLDER — regenerate via scripts/gen_cert_headers.sh */
    0x00
};
static const size_t ca_cert_der_len = sizeof(ca_cert_der);

/* ------------------------------------------------------------------
 * Server Certificate  (DER format)
 * tls_credential_add(TLS_CERT_TAG, TLS_CREDENTIAL_SERVER_CERTIFICATE, ...)
 * ------------------------------------------------------------------ */
static const unsigned char server_cert_der[] = {
    /* PLACEHOLDER — regenerate via scripts/gen_cert_headers.sh */
    0x00
};
static const size_t server_cert_der_len = sizeof(server_cert_der);

/* ------------------------------------------------------------------
 * Server Private Key  (DER PKCS#8 unencrypted format)
 * tls_credential_add(TLS_KEY_TAG, TLS_CREDENTIAL_PRIVATE_KEY, ...)
 * ------------------------------------------------------------------ */
static const unsigned char server_key_der[] = {
    /* PLACEHOLDER — regenerate via scripts/gen_cert_headers.sh */
    0x00
};
static const size_t server_key_der_len = sizeof(server_key_der);

#endif /* SENTINEL_CERTS_H */
