#!/bin/bash
# =============================================================================
# scripts/gen_cert_headers.sh
# Converts PEM certificates/keys into C byte arrays for Zephyr embedding.
#
# Run AFTER quick_start.sh has generated certs/ :
#   ./scripts/gen_cert_headers.sh
#
# Output:  drivers/certs/certs.h   (included by apps/server.c)
# =============================================================================

set -e
cd "$(dirname "$0")/.."

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
log()   { echo -e "${GREEN}[INFO] $1${NC}"; }
error() { echo -e "${RED}[ERROR] $1${NC}"; exit 1; }

OPENSSL_CMD="${OPENSSL_CMD:-openssl}"
OUT="drivers/certs/certs.h"
TMP_DIR=$(mktemp -d)
trap "rm -rf $TMP_DIR" EXIT

# ---------------------------------------------------------------------------
# Verify inputs
# ---------------------------------------------------------------------------
[ -f certs/ca.crt ]     || error "certs/ca.crt not found. Run quick_start.sh first."
[ -f certs/server.crt ] || error "certs/server.crt not found."
[ -f certs/server.key ] || error "certs/server.key not found."

log "Converting certs to DER format..."

# CA cert: PEM -> DER
$OPENSSL_CMD x509 -in certs/ca.crt -outform DER -out "$TMP_DIR/ca.der"

# Server cert: PEM -> DER
$OPENSSL_CMD x509 -in certs/server.crt -outform DER -out "$TMP_DIR/server.der"

# Server key: PKCS#1 PEM -> PKCS#8 DER (required by MbedTLS in Zephyr)
$OPENSSL_CMD pkcs8 -topk8 -nocrypt \
    -in certs/server.key -outform DER \
    -out "$TMP_DIR/server_key.der"

log "Generating $OUT ..."

# Helper: emit a C byte array from a binary file
emit_array() {
    local var_name="$1"
    local file="$2"
    printf "static const unsigned char %s[] = {\n    " "$var_name"
    xxd -i < "$file" | sed 's/  0x/0x/g; s/,$//' | tr -d '\n' \
        | sed 's/0x/\n    0x/g' | tail -n +2
    printf "\n};\n"
    printf "static const size_t %s_len = sizeof(%s);\n\n" "$var_name" "$var_name"
}

mkdir -p drivers/certs

cat > "$OUT" << 'HEADER_TOP'
#ifndef SENTINEL_CERTS_H
#define SENTINEL_CERTS_H

/*
 * drivers/certs/certs.h  —  Embedded TLS Credentials for Zephyr
 * AUTO-GENERATED by scripts/gen_cert_headers.sh — do NOT edit manually.
 *
 * Regenerate:  ./scripts/gen_cert_headers.sh
 */

HEADER_TOP

{
    printf "/* CA Certificate (DER) */\n"
    emit_array "ca_cert_der" "$TMP_DIR/ca.der"

    printf "/* Server Certificate (DER) */\n"
    emit_array "server_cert_der" "$TMP_DIR/server.der"

    printf "/* Server Private Key (DER PKCS#8 unencrypted) */\n"
    emit_array "server_key_der" "$TMP_DIR/server_key.der"
} >> "$OUT"

echo '#endif /* SENTINEL_CERTS_H */' >> "$OUT"

log "Done — $OUT updated."
log "Rebuild with:  west build -b rpi_4b ."
