#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

#include "authorization.h"
#include "sensor_manager.h"
#include "protocol.h"

#define PORT                    8080
#define MAX_CONCURRENT_SESSIONS 32

// ============================================================
// ZEPHYR BUILD  (target: rpi_4b)
// ============================================================
#ifdef __ZEPHYR__

#include <zephyr/kernel.h>
#include <zephyr/net/socket.h>
#include <zephyr/net/tls_credentials.h>
#include <zephyr/posix/pthread.h>

/*
 * TLS credential tags — arbitrary integers that pair credentials together.
 * The same set of tags is passed to TLS_SEC_TAG_LIST on the listening socket.
 */
#define TLS_CA_TAG   1
#define TLS_CERT_TAG 2
#define TLS_KEY_TAG  3

/*
 * Embedded certificate byte arrays.
 * Generated by:  ./scripts/gen_cert_headers.sh
 * Must be run after:  ./scripts/quick_start.sh
 */
#include "../drivers/certs/certs.h"

// -------------------------------------------------------
// Session slot accounting (same logic as before)
// -------------------------------------------------------
static pthread_mutex_t session_mutex = PTHREAD_MUTEX_INITIALIZER;
static int current_sessions      = 0;
static int max_observed_sessions = 0;

static int try_reserve_session_slot(void) {
    int accepted = 0;
    pthread_mutex_lock(&session_mutex);
    if (current_sessions < MAX_CONCURRENT_SESSIONS) {
        current_sessions++;
        if (current_sessions > max_observed_sessions)
            max_observed_sessions = current_sessions;
        accepted = 1;
    }
    printf("[SESSIONS] Current: %d | Max Observed: %d | Limit: %d\n",
           current_sessions, max_observed_sessions, MAX_CONCURRENT_SESSIONS);
    pthread_mutex_unlock(&session_mutex);
    return accepted;
}

static void release_session_slot(void) {
    pthread_mutex_lock(&session_mutex);
    if (current_sessions > 0)
        current_sessions--;
    printf("[SESSIONS] Current: %d | Max Observed: %d | Limit: %d\n",
           current_sessions, max_observed_sessions, MAX_CONCURRENT_SESSIONS);
    pthread_mutex_unlock(&session_mutex);
}

// -------------------------------------------------------
// Per-client session state passed to worker thread
// -------------------------------------------------------
typedef struct {
    int                client_fd;
    SensorManager     *sensor_mgr;
    struct sockaddr_in client_addr;
} ClientSession;

// -------------------------------------------------------
// Worker thread: handles one authenticated TLS client
// -------------------------------------------------------
static void *client_session_thread(void *arg) {
    ClientSession *session = (ClientSession *)arg;
    ClientIdentity id;
    char ip_buf[INET_ADDRSTRLEN] = {0};

    zsock_inet_ntop(AF_INET, &session->client_addr.sin_addr,
                    ip_buf, sizeof(ip_buf));
    printf("[CONN] Worker started for %s\n", ip_buf);

    /*
     * In Zephyr TLS, zsock_accept() returns a socket whose TLS handshake
     * completes on the first send/recv.  authorize_client() triggers the
     * handshake implicitly by calling getsockopt(TLS_NATIVE) which forces
     * the handshake to complete, then extracts CN/OU from the peer cert.
     */
    if (authorize_client(session->client_fd, &id) == 0) {
        if (id.role != ROLE_UNAUTHORIZED) {
            printf("[AUTH] GRANTED — User: '%s' | Role: '%s'\n",
                   id.common_name, role_to_string(id.role));

            ProtocolContext pctx;
            protocol_init(&pctx, session->client_fd, id, session->sensor_mgr);
            protocol_run(&pctx);

            printf("[CONN] Session ended for '%s'\n", id.common_name);
        } else {
            printf("[AUTH] DENIED — unauthorized role for '%s'\n", id.common_name);
        }
    } else {
        printf("[AUTH] DENIED — missing/invalid certificate from %s\n", ip_buf);
    }

    printf("[CONN] Closing fd for %s\n", ip_buf);
    zsock_close(session->client_fd);
    free(session);
    release_session_slot();
    return NULL;
}

// -------------------------------------------------------
// Load embedded certs into Zephyr's credential store
// -------------------------------------------------------
static int setup_tls_credentials(void) {
    int ret;

    ret = tls_credential_add(TLS_CA_TAG,
                             TLS_CREDENTIAL_CA_CERTIFICATE,
                             ca_cert_der, ca_cert_der_len);
    if (ret < 0) { printf("[TLS] CA cert add failed: %d\n", ret); return ret; }

    ret = tls_credential_add(TLS_CERT_TAG,
                             TLS_CREDENTIAL_SERVER_CERTIFICATE,
                             server_cert_der, server_cert_der_len);
    if (ret < 0) { printf("[TLS] Server cert add failed: %d\n", ret); return ret; }

    ret = tls_credential_add(TLS_KEY_TAG,
                             TLS_CREDENTIAL_PRIVATE_KEY,
                             server_key_der, server_key_der_len);
    if (ret < 0) { printf("[TLS] Server key add failed: %d\n", ret); return ret; }

    printf("[TLS] Credentials loaded (CA=%d, CERT=%d, KEY=%d)\n",
           TLS_CA_TAG, TLS_CERT_TAG, TLS_KEY_TAG);
    return 0;
}

// -------------------------------------------------------
// Create, configure, bind, and listen on a TLS socket
// -------------------------------------------------------
static int create_tls_listen_socket(int port) {
    /* TLS 1.2 server socket — Zephyr's mbedTLS stack handles the handshake */
    int sock = zsock_socket(AF_INET, SOCK_STREAM, IPPROTO_TLS_1_2);
    if (sock < 0) {
        printf("[ERROR] zsock_socket failed: %d\n", sock);
        return -1;
    }

    /* Bind credential tags to this socket */
    sec_tag_t tags[] = { TLS_CA_TAG, TLS_CERT_TAG, TLS_KEY_TAG };
    zsock_setsockopt(sock, SOL_TLS, TLS_SEC_TAG_LIST, tags, sizeof(tags));

    /* Require client certificate (mTLS) */
    int peer_verify = TLS_PEER_VERIFY_REQUIRED;
    zsock_setsockopt(sock, SOL_TLS, TLS_PEER_VERIFY,
                     &peer_verify, sizeof(peer_verify));

    /* Allow port reuse on restart */
    int opt = 1;
    zsock_setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    struct sockaddr_in addr = {
        .sin_family      = AF_INET,
        .sin_port        = htons(port),
        .sin_addr.s_addr = htonl(INADDR_ANY)
    };

    if (zsock_bind(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        printf("[ERROR] Bind failed\n");
        zsock_close(sock);
        return -1;
    }

    if (zsock_listen(sock, 5) < 0) {
        printf("[ERROR] Listen failed\n");
        zsock_close(sock);
        return -1;
    }

    return sock;
}

// -------------------------------------------------------
// Zephyr application entry point
// -------------------------------------------------------
int main(void) {
    SensorManager sensor_mgr;

    printf("====================================================\n");
    printf("   Sentinel-RT Monitoring System (Zephyr / RPi 4)  \n");
    printf("====================================================\n");

    /* 1. Init hardware + background 1 kHz polling thread */
    if (manager_init(&sensor_mgr) != 0) {
        printf("[FATAL] Sensor manager init failed\n");
        return 1;
    }
    printf("[SYSTEM] Polling active (Vib:GPIO%d Snd:GPIO%d Temp:GPIO%d Cur:I2C)\n",
           PIN_VIBRATION, PIN_SOUND, PIN_TEMP_1W);

    /* 2. Load embedded TLS credentials */
    if (setup_tls_credentials() != 0) {
        printf("[FATAL] TLS credential setup failed\n");
        return 1;
    }

    /* 3. Create mTLS listening socket */
    int sock = create_tls_listen_socket(PORT);
    if (sock < 0) {
        printf("[FATAL] Cannot create TLS socket\n");
        return 1;
    }
    printf("[NETWORK] Listening on port %d (mTLS)\n", PORT);

    /* 4. Accept loop — each client gets a detached pthread */
    while (1) {
        struct sockaddr_in addr;
        socklen_t len = sizeof(addr);

        printf("\n[NETWORK] Waiting for connection...\n");
        int client_fd = zsock_accept(sock, (struct sockaddr *)&addr, &len);
        if (client_fd < 0) {
            printf("[ERROR] Accept failed: %d\n", client_fd);
            continue;
        }

        char ip_buf[INET_ADDRSTRLEN] = {0};
        zsock_inet_ntop(AF_INET, &addr.sin_addr, ip_buf, sizeof(ip_buf));
        printf("[CONN] TCP connection from %s\n", ip_buf);

        if (!try_reserve_session_slot()) {
            printf("[SESSIONS] Limit reached, rejecting %s\n", ip_buf);
            zsock_close(client_fd);
            continue;
        }

        ClientSession *session = malloc(sizeof(ClientSession));
        if (!session) {
            printf("[ERROR] OOM allocating session\n");
            zsock_close(client_fd);
            release_session_slot();
            continue;
        }

        session->client_fd   = client_fd;
        session->sensor_mgr  = &sensor_mgr;
        session->client_addr = addr;

        pthread_t tid;
        if (pthread_create(&tid, NULL, client_session_thread, session) != 0) {
            printf("[ERROR] pthread_create failed\n");
            zsock_close(client_fd);
            free(session);
            release_session_slot();
            continue;
        }
        pthread_detach(tid);
    }

    /* Unreachable in normal operation */
    zsock_close(sock);
    manager_cleanup(&sensor_mgr);
    return 0;
}

// ============================================================
// LINUX / LEGACY BUILD  (kept so client.c cross-compiles cleanly)
// ============================================================
#else  /* !__ZEPHYR__ */

#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <signal.h>
#include <openssl/ssl.h>
#include <openssl/err.h>

#define SERVER_CERT "certs/server.crt"
#define SERVER_KEY  "certs/server.key"
#define CA_CERT     "certs/ca.crt"

typedef struct {
    int                client_fd;
    SSL_CTX           *ssl_ctx;
    SensorManager     *sensor_mgr;
    struct sockaddr_in client_addr;
} ClientSession;

static pthread_mutex_t session_mutex      = PTHREAD_MUTEX_INITIALIZER;
static int             current_sessions   = 0;
static int             max_observed_sessions = 0;

static int try_reserve_session_slot(void) {
    int ok = 0;
    pthread_mutex_lock(&session_mutex);
    if (current_sessions < MAX_CONCURRENT_SESSIONS) {
        current_sessions++;
        if (current_sessions > max_observed_sessions)
            max_observed_sessions = current_sessions;
        ok = 1;
    }
    printf("[SESSIONS] Current: %d | Max: %d | Limit: %d\n",
           current_sessions, max_observed_sessions, MAX_CONCURRENT_SESSIONS);
    pthread_mutex_unlock(&session_mutex);
    return ok;
}

static void release_session_slot(void) {
    pthread_mutex_lock(&session_mutex);
    if (current_sessions > 0) current_sessions--;
    printf("[SESSIONS] Current: %d | Max: %d | Limit: %d\n",
           current_sessions, max_observed_sessions, MAX_CONCURRENT_SESSIONS);
    pthread_mutex_unlock(&session_mutex);
}

static void *client_session_thread(void *arg) {
    ClientSession *session = (ClientSession *)arg;
    ClientIdentity id;
    char ip_buf[INET_ADDRSTRLEN] = {0};
    inet_ntop(AF_INET, &session->client_addr.sin_addr, ip_buf, sizeof(ip_buf));

    SSL *ssl = SSL_new(session->ssl_ctx);
    if (!ssl) { close(session->client_fd); free(session); return NULL; }

    SSL_set_fd(ssl, session->client_fd);
    if (SSL_accept(ssl) <= 0) {
        ERR_print_errors_fp(stderr);
    } else if (authorize_client(ssl, &id) == 0 && id.role != ROLE_UNAUTHORIZED) {
        printf("[AUTH] GRANTED — %s (%s)\n", id.common_name, role_to_string(id.role));
        ProtocolContext pctx;
        protocol_init(&pctx, ssl, id, session->sensor_mgr);
        protocol_run(&pctx);
    }

    SSL_shutdown(ssl);
    SSL_free(ssl);
    close(session->client_fd);
    free(session);
    release_session_slot();
    return NULL;
}

int main(void) {
    signal(SIGPIPE, SIG_IGN);
    SSL_load_error_strings();
    OpenSSL_add_ssl_algorithms();

    SSL_CTX *ctx = SSL_CTX_new(TLS_server_method());
    SSL_CTX_use_certificate_file(ctx, SERVER_CERT, SSL_FILETYPE_PEM);
    SSL_CTX_use_PrivateKey_file(ctx, SERVER_KEY,   SSL_FILETYPE_PEM);
    SSL_CTX_load_verify_locations(ctx, CA_CERT, NULL);
    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT, NULL);

    struct sockaddr_in addr = {
        .sin_family      = AF_INET,
        .sin_port        = htons(PORT),
        .sin_addr.s_addr = htonl(INADDR_ANY)
    };
    int sock = socket(AF_INET, SOCK_STREAM, 0);
    int opt = 1;
    setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    bind(sock,   (struct sockaddr *)&addr, sizeof(addr));
    listen(sock, 5);

    SensorManager sensor_mgr;
    if (manager_init(&sensor_mgr) != 0) return 1;

    while (1) {
        struct sockaddr_in caddr;
        unsigned int clen = sizeof(caddr);
        int cfd = accept(sock, (struct sockaddr *)&caddr, &clen);
        if (cfd < 0) continue;
        if (!try_reserve_session_slot()) { close(cfd); continue; }

        ClientSession *s = malloc(sizeof(ClientSession));
        s->client_fd   = cfd;
        s->ssl_ctx     = ctx;
        s->sensor_mgr  = &sensor_mgr;
        s->client_addr = caddr;

        pthread_t tid;
        if (pthread_create(&tid, NULL, client_session_thread, s) != 0) {
            close(cfd); free(s); release_session_slot();
        } else {
            pthread_detach(tid);
        }
    }

    close(sock);
    SSL_CTX_free(ctx);
    manager_cleanup(&sensor_mgr);
    return 0;
}

#endif  /* __ZEPHYR__ */
